#!/usr/bin/env ruby
# Copyright 2009-2010 Michael D. Ivey <ivey@gweezlebur.com>
# DWTFYW

require 'rubygems'
require 'twitter'
require 'sqlite3'

auth = YAML.load(File.open(File.dirname(__FILE__) + "/auth.yml"))
db = SQLite3::Database.new(File.dirname(__FILE__) + "/favorites.db")

db.execute_batch "create table if not exists favorites (guid string)"

oauth = Twitter::OAuth.new(auth['app']['consumer_key'], auth['app']['consumer_secret'])
oauth.authorize_from_access(auth['main']['token'], auth['main']['secret'])
main = Twitter::Base.new oauth

oauth = Twitter::OAuth.new(auth['app']['consumer_key'], auth['app']['consumer_secret'])
oauth.authorize_from_access(auth['favs']['token'], auth['favs']['secret'])
favs = Twitter::Base.new oauth

count = 1

main.favorites(:count => 200).reverse.each do |i|
  unless db.get_first_row("select * from favorites where guid = '#{i.id}'")
    db.execute "insert into favorites values ('#{i.id}')"
    if ENV.has_key? "FAV2RT_PROMPT"
      print "#{i.user.screen_name}: #{i.text} (#{i.id})  > "
      next unless (gets.chomp.downcase == "y")
    end

    favs.retweet i.id
    count += 1
    sleep 5
  end
  exit if count > 1
end
