#!/usr/bin/env ruby
# Written by Michael D. Ivey <ivey@gweezlebur.com>
# Released into the public domain
#
# Step 1: Make an OAuth application at Twitter Dev portal
# Step 2: Use twurl to get keys for main account and the RT account
# Step 3: Copy auth.yml.sample to auth.yml, and add various keys
# Step 4: Run script
#  
# auth.yml format:
#  app:
#    consumer_key: 
#    consumer_secret: 
#  main:
#    user: ivey
#    token: 
#    secret: 
#  favs:
#    user: iveyfavs
#    token: 
#    secret: 
#  
# You can also set page: 2 or page: 3 if you want to get favs older than
# the last 200. You can manually tweak this as needed to find the right RTs

require 'rubygems'
require 'twitter'
require 'sqlite3'
require 'yaml'

auth = YAML.load(File.open(File.dirname(__FILE__) + "/auth.yml"))
db = SQLite3::Database.new(File.dirname(__FILE__) + "/favorites.db")

db.execute_batch "create table if not exists favorites (guid string)"

main = Twitter::REST::Client.new do |config|
  config.consumer_key        = auth['app']['consumer_key']
  config.consumer_secret     = auth['app']['consumer_secret']
  config.access_token        = auth['main']['token']
  config.access_token_secret = auth['main']['secret']
end

favs = Twitter::REST::Client.new do |config|
  config.consumer_key        = auth['app']['consumer_key']
  config.consumer_secret     = auth['app']['consumer_secret']
  config.access_token        = auth['favs']['token']
  config.access_token_secret = auth['favs']['secret']
end

count = 1

opts = {:count => 200}
opts[:page] = auth['page'] if auth['page']

main.favorites(opts).reverse.each do |i|
  unless db.get_first_row("select * from favorites where guid = '#{i.id}'")
    db.execute "insert into favorites values ('#{i.id}')"
    if ENV.has_key? "FAV2RT_PROMPT"
      print "#{i.user.screen_name}: #{i.text} (#{i.id})  > "
      next unless (gets.chomp.downcase == "y")
    end

    favs.retweet i.id
    print "#{i.user.screen_name}: #{i.text} (#{i.id})" if auth['debug']
    count += 1
    sleep 5
  end
  exit if count > 1
end
