#!/usr/bin/env ruby
# Copyright 2009-2010 Michael D. Ivey <ivey@gweezlebur.com>
# DWTFYW

require 'rubygems'
require 'twitter'
require 'sqlite3'

auth = YAML.load(File.open(File.dirname(__FILE__) + "/auth.yml"))
db = SQLite3::Database.new(File.dirname(__FILE__) + "/favorites.db")

db.execute_batch "create table if not exists favorites (guid string)"

main = Twitter::Base.new(Twitter::HTTPAuth.new(auth['main']['user'],
                                               auth['main']['pass'],
                                               :ssl => true))
favs = Twitter::Base.new(Twitter::HTTPAuth.new(auth['favs']['user'],
                                               auth['favs']['pass'],
                                               :ssl => true))

count = 1

main.favorites.reverse.each do |i|
  unless db.get_first_row("select * from favorites where guid = '#{i.id}'")
    db.execute "insert into favorites values ('#{i.id}')"
    favs.retweet i.id 
    count += 1
    sleep 5
  end
  exit if count > 1
end
